urls.py
# -*- coding: utf-8 -*-

from django.urls import path, include
from . import views

app_name = 'worktracker'

urlpatterns = [
    path('', views.control, name='control'),
    path('start/', views.start, name='start'),
    path('stop/', views.stop, name='stop'),
    path('client-report/', views.report, name='client-report'),
    path('project-report/', views.reportproject, name='project-report')
]

models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Client(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Project(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT,
                               related_name='projects')
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    class Meta:
        ordering = ['client__name', 'name']

    def __str__(self):
        return '%s - %s' % (self.client.name, self.name)


class WorkCategory(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'work categories'
        ordering = ['name']

    def __str__(self):
        return self.name


class Block(models.Model):
    start = models.DateTimeField(default=timezone.now, db_index=True)
    end = models.DateTimeField(null=True, blank=True, db_index=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT,
                                related_name='blocks')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                             related_name='work_blocks', db_index=True)
    cat = models.ForeignKey(WorkCategory, on_delete=models.PROTECT,
                            related_name='blocks', db_index=True)
    description = models.TextField(blank=True)
    class Meta:
        ordering = ['-start']

    def __str__(self):
        return '{self.project} - {self.start:%Y-%m-%d %H:%M}'.format(**locals())

    def duration(self):
        if self.end:
            return self.end - self.start
        else:
            return timezone.now() - self.start

forms.py
# -*- coding: utf-8 -*-

from django import forms
from datetime import timedelta
from django.contrib.auth import get_user_model

from .models import Block, Client


class BlockForm(forms.ModelForm):
    class Meta:
        model = Block
        fields = ('project', 'cat', 'description')


class ReportForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=get_user_model().objects.all(),
        empty_label='All', required=False)
    start = forms.DateField()
    end = forms.DateField()
    #clients = forms.ModelChoiceField(Client.objects.all())

views.py
import datetime
from collections import defaultdict

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages

from .models import Client, Project, WorkCategory, Block
from .forms import BlockForm, ReportForm




def current_block(user):
    block = Block.objects.filter(user=user).order_by('-start').first()
    if block is not None:
        return block, not bool(block.end)
    return None, False

def get_recent_blocks(user):
    start = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
    return Block.objects.filter(user=user, start__gte=start).select_related(
        'project', 'project__client')
    
    

@login_required
def control(request):
    block, current = current_block(request.user)
    recent_blocks = get_recent_blocks(request.user)
    if not block:
        start_form = BlockForm()
    elif block.end:
        start_form = BlockForm(
            initial={'project': block.project, 'cat': block.cat})
    else:
        start_form = None
    return render(request, 'worktracker/control.html', {
        'start_form': start_form,
        'time_block': block if current else None})


@login_required
def start(request):
    block, current = current_block(request.user)
    if current:
        messages.error(request, 'Already running block')
        return redirect('worktracker:control')
    start_form = BlockForm(request.POST or None)
    if start_form.is_valid():
        block = start_form.save(commit=False)
        block.user = request.user
        block.save()
        return redirect('worktracker:control')
    return render(request, 'worktracker/control.html', {
        'start_form': start_form})


@login_required
def stop(request):
    block, _ = current_block(request.user)
    if not block:
        messages.error(request, 'No current work to stop')
        return redirect('worktracker:control')
    if not request.POST:
        return redirect('worktracker:control')
    block.end = timezone.now()
    block.save()
    return redirect('worktracker:control')


# TODO replace below with queries with annotations
# TODO abstract out - not DRY
def blocks_by_client(user, start, end):
    clients = Client.objects.all()
    for client in clients:
        blocks = Block.objects.filter(start__range=(
            datetime.datetime.combine(start, datetime.time.min),
            datetime.datetime.combine(end, datetime.time.max)),
            project__client=client
        )
        if user:
            blocks = blocks.filter(user=user)
        client.total_time = sum((b.duration() for b in blocks),
                                datetime.timedelta(0))
    grand_total = sum((c.total_time for c in clients), datetime.timedelta(0)) 
    return clients, grand_total


def blocks_by_project(user, start, end):
    projects = Project.objects.all()
    for project in projects:
        blocks = Block.objects.filter(start__range=(
            datetime.datetime.combine(start, datetime.time.min),
            datetime.datetime.combine(end, datetime.time.max)),
            project=project
        )
        if user:
            blocks = blocks.filter(user=user)
        project.total_time = sum ((b.duration() for b in blocks),
                                  datetime.timedelta(0))
    grand_total = sum((c.total_time for c in projects), datetime.timedelta(0)) 
    return projects, grand_total


@login_required
def report(request):
    today = datetime.date.today()
    form = ReportForm(request.POST or None,
                      initial = {'user': request.user, 'start': today, 'end': today})
    if form.is_valid():
        clients, grand_total = blocks_by_client(
            form.cleaned_data['user'],
            form.cleaned_data['start'], form.cleaned_data['end'],
        )
    else:
        clients, grand_total = blocks_by_client(request.user, today, today)
    return render(request, 'worktracker/report.html',
                  {'form': form, 'clients': clients, 'grand_total': grand_total})
    

@login_required
def reportproject(request):
    today = datetime.date.today()
    form = ReportForm(request.POST or None,
                      initial = {'user': request.user, 'start': today, 'end': today})
    if form.is_valid():
        projects, grand_total = blocks_by_project(
            form.cleaned_data['user'], form.cleaned_data['start'],
            form.cleaned_data['end'])
    else:
        projects, grand_total = blocks_by_project(request.user, today, today)
    return render(request, 'worktracker/reportproject.html',
                  {'form': form, 'projects': projects, 'grand_total': grand_total})

templates/worktracker/control.html
{% extends 'base.html' %}

{% load worktracker_tags %}

{% block title %}<title>Time track controls</title>{% endblock %}

{%block content%}
    <div class="container">
    {% if time_block %}
        <h1>Current block</h1>
        <div class="row">
            <div class="col-3">
                {{time_block.project}}
            </div>
            <div class="col-3">
                {{time_block.cat}}
            </div>
            <div class="col-3">
                {{time_block.duration|hhmm}}
            </div>
        <div class="row">
            <div class="col-12">
                <form action="{%url 'worktracker:stop'%}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <button class="btn btn-primary">Stop</button>
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <h1>Start block</h1>
        <div class="row">
            <div class="col-12">
                <form action="{%url 'worktracker:start'%}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{start_form.as_p}}
                        <button class="btn btn-primary">Start</button>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
    {%comment%} Not currently working in view
	<h1>Recent blocks</h1>
        <div class="row">
            <div class="col-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <table class="table">
                        {{form.as_table}}
                        </table>
                        <button class="btn btn-primary">View</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <table class="table">
        <tr><th>Project</th><th>Client</th><th>Time</th></tr>
        {% for recent_block in recent_blocks %}
            <tr><td>{{recent_block.project.name}}</td><td>{{recent_block.project.client.name}}</td><td>{{recent_block.duration}}</td></tr>
        {% endfor %}
    </table>
    {%endcomment%}
{% endblock %}

templates/worktracker/report.html
{% extends 'base.html' %}

{% load worktracker_tags %}

{% block title %}<title>Time track report</title>{% endblock %}

{%block content%}
    <div class="container">
        <h1>Report by client</h1>
        <div class="row">
            <div class="col-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <table class="table">
                        {{form.as_table}}
                        </table>
                        <button class="btn btn-primary">View</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <table class="table">
        <tr><th>Client</th><th>Total Time</th></tr>
        {% for client in clients %}
            <tr><td>{{client}}</td><td>{{client.total_time|hhmm}}</td></tr>
        {% endfor %}
	<tr><th>Total</th><td>{{grand_total|hhmm}}</td></tr>
    </table>
{% endblock %}

templates/worktracker/reportproject.html
{% extends 'base.html' %}

{% load worktracker_tags %}

{% block title %}<title>Time track report</title>{% endblock %}

{%block content%}
    <div class="container">
        <h1>Report by project</h1>
        <div class="row">
            <div class="col-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <table class="table">
                        {{form.as_table}}
                        </table>
                        <button class="btn btn-primary">View</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <table class="table">
        <tr><th>Project</th><th>Total Time</th></tr>
        {% for project in projects %}
            <tr><td>{{project}}</td><td>{{project.total_time|hhmm}}</td></tr>
        {% endfor %}
	<tr><th>Total</th><td>{{grand_total|hhmm}}</td></tr>
    </table>
{% endblock %}